-- @noindex  (a development tool, not a package: never installed)
-- Records where every control lands, so a change to the layout code can
-- be held to "every existing layout stays exactly as it is".
--
--     lua dev/TS_CV_LayoutSnap.lua <TS_ChannelView_Mappings.ini> [out]
--
-- reads each plugin's control list from a layout library, adds a set of
-- made-up layouts that poke at the corners (dividers at either end, a
-- half-gap that lands on a column's last half-row, a fader between two
-- sections ...), lays every one out with TS_CV_Panel.layout in both
-- flows at one to six rows, and writes the lot to TS_CV_LayoutFixture.lua
-- beside this file. TS_CV_Test.lua then lays the same lists out again and
-- checks every position, rule and width against the file. Run this only
-- to record a NEW baseline -- before a layout change, never after it.

local HERE = debug.getinfo(1, "S").source:match("@?(.*[\\/])") or "./"
package.path = HERE .. "../?.lua;" .. package.path
reaper = setmetatable({}, { __index = function() return function() return nil end end })

local P = require("TS_CV_Panel")
local C = require("TS_CV_Config")

local ini_path = arg[1]
local out_path = arg[2] or (HERE .. "TS_CV_LayoutFixture.lua")

-- A control list as a short string: one letter per control, "!" after a
-- divider that draws no rule. Enough for the layout, which only ever asks
-- a control its type (and a divider whether it has a rule).
local LETTER = { knob = "k", toggle = "t", combo = "c", stepped = "s", fader = "f",
                 blank = "b", divider = "d", half_gap = "h" }
local TYPE = {}
for t, l in pairs(LETTER) do TYPE[l] = t end

local function read_ini(p)
  local f = assert(io.open(p, "rb"), "can't read " .. tostring(p))
  local txt = f:read("a"); f:close()
  local out, cur = {}, nil
  for line in txt:gmatch("[^\r\n]+") do
    local sect = line:match("^%[(.+)%]%s*$")
    if sect then cur = { name = sect, ctl = {} }; out[#out + 1] = cur
    elseif cur then
      local n, rest = line:match("^Ctl(%d+)=(.*)$")
      if n then
        local _, ty, flags = rest:match("^([^|]*)|([^|]*)|([^|]*)")
        cur.ctl[tonumber(n) + 1] = { type = ty, no_rule = ((tonumber(flags) or 0) & 4) ~= 0 }
      end
    end
  end
  local cases = {}
  for _, s in ipairs(out) do
    local t = {}
    for _, c in ipairs(s.ctl) do
      local l = LETTER[c.type] or "k"
      t[#t + 1] = l .. ((c.type == "divider" and c.no_rule) and "!" or "")
    end
    if #t > 0 then cases[#cases + 1] = { name = s.name, ctl = table.concat(t) } end
  end
  return cases
end

local SYNTH = {
  { name = "empty", ctl = "" },
  { name = "one", ctl = "k" },
  { name = "seven", ctl = "kkkkkkk" },
  { name = "lead and trail dividers", ctl = "dkkkd" },
  { name = "double divider", ctl = "kkddkk" },
  { name = "silent divider", ctl = "kkd!kk" },
  { name = "gap first", ctl = "hkkk" },
  { name = "gap last", ctl = "kkkh" },
  { name = "gaps only", ctl = "hh" },
  { name = "gap pairs", ctl = "khkhkhk" },
  { name = "two gaps", ctl = "kkhhkk" },
  { name = "fader between", ctl = "kkfkk" },
  { name = "fader first and last", ctl = "fkkf" },
  { name = "faders only", ctl = "ff" },
  { name = "mixed", ctl = "kthcsbkd!khkfkkdtt" },
}

local function parse(s)
  local ctl, i = {}, 1
  while i <= #s do
    local l = s:sub(i, i)
    local c = { type = TYPE[l] }
    if s:sub(i + 1, i + 1) == "!" then c.no_rule = true; i = i + 1 end
    ctl[#ctl + 1] = c
    i = i + 1
  end
  return ctl
end

local cases = ini_path and read_ini(ini_path) or {}
for _, s in ipairs(SYNTH) do cases[#cases + 1] = s end

-- the baseline is the original 58 px column, whatever the default is now
C.set_cell_w(58)

-- rows straight in, rather than a panel height
local rows_for = P.rows_for
P.rows_for = function(r) return r end

local function snap(ctl_str, flow, rows)
  C.FLOW = flow
  local ctl = parse(ctl_str)
  local idx = {}
  for i, c in ipairs(ctl) do idx[c] = i end
  local lay = P.layout(ctl, rows)
  local items = {}
  for _, it in ipairs(lay.items) do
    items[#items + 1] = string.format("%d,%g,%g", idx[it.ctl], it.x, it.y)
  end
  local rules = {}
  for _, r in ipairs(lay.rules) do rules[#rules + 1] = string.format("%g", r) end
  return string.format("{ i = %q, r = %q, w = %g, h = %g }",
    table.concat(items, " "), table.concat(rules, " "), lay.width, lay.height)
end

local out = { "-- @noindex  (generated by TS_CV_LayoutSnap.lua: the layout baseline)",
              "-- i: control index,x,y for each placed control; r: rule x offsets;",
              "-- w: grid width; h: grid height. Keys: case|flow|rows.",
              "return {", "  cases = {" }
for _, c in ipairs(cases) do
  out[#out + 1] = string.format("    { name = %q, ctl = %q },", c.name, c.ctl)
end
out[#out + 1] = "  },"
out[#out + 1] = "  expect = {"
for ci, c in ipairs(cases) do
  for _, flow in ipairs({ "column", "row" }) do
    for rows = 1, 6 do
      out[#out + 1] = string.format("    [%q] = %s,", ci .. "|" .. flow .. "|" .. rows, snap(c.ctl, flow, rows))
    end
  end
end
out[#out + 1] = "  },"
out[#out + 1] = "}"
P.rows_for = rows_for

local f = assert(io.open(out_path, "wb"))
f:write(table.concat(out, "\n"), "\n"); f:close()
print(("%d layouts, %d snapshots -> %s"):format(#cases, #cases * 12, out_path))
